### ISSUE TITLE
Password Reset not working

### ISSUE THREAD

**Issue by CB4SAP** [eclipse-tractusx/portal#282]
### Current Behavior
When I try to change the initial password to logon to the portal, in the password screen the "Submit" Button is always greyed out.
The Browser Console shows an error:

Main.js:389 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at FormUpdate.setItems (Main.js:389:76)
    at FormUpdate.<anonymous> (Main.js:356:18)
![image](https://github.com/eclipse-tractusx/portal/assets/92523983/34dcd1e1-411c-40c8-8892-aab5b1c10265)

### Expected Behavior
Submit button should not be greyed out and password change should be possible.

### Steps To Reproduce
create a new user, try to access.

**Comment by CB4SAP** [comment]
duplicate to 
https://github.com/eclipse-tractusx/portal-iam/issues/108

therefore closed.
